name: bangketicketmobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.0
  image: ^3.0.1
  http: ^1.2.2
  flutter_blue_plus: ^1.32.12
  permission_handler: ^10.2.0
  bluetooth_print: ^3.0.1
  blue_thermal_printer: ^1.2.3
  cupertino_icons: ^1.0.8
  android_intent_plus: ^3.0.2
  intl: ^0.18.0 
  flutter_native_splash: ^2.1.1

flutter_native_splash:
  color: "#ffffff" # Background color (use your preferred color)
  image: assets/logo.png # Path to your BangkeTicket logo
  android: true
  ios: true
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo.png
    - assets/logo-bw.png
    - assets/malolos-logo.png
    - assets/malolos.png
    - assets/malolos-bw.png
    - assets/background.png

  uses-material-design: true
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/static/Montserrat-Regular.ttf

